export const Places = [
  {
    id: "1",
    district: "Anantapur",
    places: [
      {
        id: "101",
        destination_name: "Lepakshi Temple",
        destination_category_id: "1",
        city_id: "101",
        name: "Heritage",
        hub_name: "Anantapur Zone",
        hub_id: "1",
        thumb_image: "lepakshi_temple_thumb.jpg",
        path: "",
        latitude: "13.8133",
        longitude: "77.6097",
        map_icon: "FaLandmark",
        slug: "lepakshi-temple",
        approx_time_to_visit: "2 hours",
        map_image_path: [
          "https://s7ap1.scene7.com/is/image/incredibleindia/lepakshi-anantapur-ap-1-attr-hero?qlt=82&ts=1726743954484",
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnRfAs11w6crR8z2yiTvIpoEckWPbl5Snmmw&s",
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7o_9-cdY6WMcumaHYgwMnY1tsR1XWJ-XMVg&s",
        ],
        city: "Lepakshi",
      },
      {
        id: "102",
        destination_name: "Puttaparthi (Prasanthi Nilayam)",
        destination_category_id: "2",
        city_id: "102",
        name: "Religious",
        hub_name: "Anantapur Zone",
        hub_id: "1",
        thumb_image: "puttaparthi_thumb.jpg",
        path: "",
        latitude: "14.1652",
        longitude: "77.8118",
        map_icon: "FaRegFlag",
        slug: "puttaparthi-prasanthi-nilayam",
        approx_time_to_visit: "3 hours",
        map_image_path: "https://example.com/images/puttaparthi.jpg",
        city: "Puttaparthi",
      },
      {
        id: "103",
        destination_name: "Gooty Fort",
        destination_category_id: "1",
        city_id: "103",
        name: "Heritage",
        hub_name: "Anantapur Zone",
        hub_id: "1",
        thumb_image: "gooty_fort_thumb.jpg",
        path: "",
        latitude: "15.1214",
        longitude: "77.6337",
        map_icon: "FaLandmark",
        slug: "gooty-fort",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/gooty_fort.jpg",
        city: "Gooty",
      },
      {
        id: "104",
        destination_name: "Penukonda Fort",
        destination_category_id: "1",
        city_id: "104",
        name: "Heritage",
        hub_name: "Anantapur Zone",
        hub_id: "1",
        thumb_image: "penukonda_fort_thumb.jpg",
        path: "",
        latitude: "14.0833",
        longitude: "77.5833",
        map_icon: "FaLandmark",
        slug: "penukonda-fort",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/penukonda_fort.jpg",
        city: "Penukonda",
      },
      {
        id: "105",
        destination_name: "Thimmamma Marrimanu",
        destination_category_id: "3",
        city_id: "105",
        name: "Nature",
        hub_name: "Anantapur Zone",
        hub_id: "1",
        thumb_image: "thimmamma_marrimanu_thumb.jpg",
        path: "",
        latitude: "14.0333",
        longitude: "78.3167",
        map_icon: "aUmbrellaBeach",
        slug: "thimmamma-marrimanu",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/thimmamma_marrimanu.jpg",
        city: "Anantapur",
      },
    ],
  },
  {
    id: "2",
    district: "Chittoor",
    places: [
      {
        id: "201",
        destination_name: "Tirupati Balaji Temple",
        destination_category_id: "2",
        city_id: "201",
        name: "Religious",
        hub_name: "Chittoor Zone",
        hub_id: "2",
        thumb_image: "tirupati_balaji_thumb.jpg",
        path: "",
        latitude: "13.6784",
        longitude: "79.3531",
        map_icon: "FaRegFlag",
        slug: "tirupati-balaji-temple",
        approx_time_to_visit: "4 hours",
        map_image_path:
          "https://tse2.mm.bing.net/th?id=OIP.Z2Q9tHq43TT_a0MUmS3HbAHaFj&pid=Api",
        city: "Tirupati",
      },
      {
        id: "202",
        destination_name: "Sri Venkateswara National Park",
        destination_category_id: "3",
        city_id: "202",
        name: "Nature",
        hub_name: "Chittoor Zone",
        hub_id: "2",
        thumb_image: "sri_venkateswara_park_thumb.jpg",
        path: "",
        latitude: "13.6391",
        longitude: "79.3987",
        map_icon: "aUmbrellaBeach",
        slug: "sri-venkateswara-national-park",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/sri_venkateswara_park.jpg",
        city: "Tirupati",
      },
      {
        id: "203",
        destination_name: "Chandragiri Fort",
        destination_category_id: "1",
        city_id: "203",
        name: "Heritage",
        hub_name: "Chittoor Zone",
        hub_id: "2",
        thumb_image: "chandragiri_fort_thumb.jpg",
        path: "",
        latitude: "13.5833",
        longitude: "79.3167",
        map_icon: "FaLandmark",
        slug: "chandragiri-fort",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/chandragiri_fort.jpg",
        city: "Chandragiri",
      },
      {
        id: "204",
        destination_name: "Silathoranam",
        destination_category_id: "3",
        city_id: "204",
        name: "Nature",
        hub_name: "Chittoor Zone",
        hub_id: "2",
        thumb_image: "silathoranam_thumb.jpg",
        path: "",
        latitude: "13.6833",
        longitude: "79.3667",
        map_icon: "aUmbrellaBeach",
        slug: "silathoranam",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/silathoranam.jpg",
        city: "Tirupati",
      },
      {
        id: "205",
        destination_name: "Kailasanatha Kona Waterfalls",
        destination_category_id: "3",
        city_id: "205",
        name: "Nature",
        hub_name: "Chittoor Zone",
        hub_id: "2",
        thumb_image: "kailasanatha_kona_thumb.jpg",
        path: "",
        latitude: "13.5833",
        longitude: "79.3167",
        map_icon: "aUmbrellaBeach",
        slug: "kailasanatha-kona-waterfalls",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/kailasanatha_kona.jpg",
        city: "Chittoor",
      },
    ],
  },
  {
    id: "3",
    district: "East Godavari",
    places: [
      {
        id: "301",
        destination_name: "Kadiyam Nurseries",
        destination_category_id: "3",
        city_id: "301",
        name: "Nature",
        hub_name: "East Godavari Zone",
        hub_id: "3",
        thumb_image: "kadiyam_nurseries_thumb.jpg",
        path: "",
        latitude: "16.9167",
        longitude: "81.8333",
        map_icon: "aUmbrellaBeach",
        slug: "kadiyam-nurseries",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/kadiyam_nurseries.jpg",
        city: "Kadiyam",
      },
      {
        id: "302",
        destination_name: "Papi Hills",
        destination_category_id: "3",
        city_id: "302",
        name: "Nature",
        hub_name: "East Godavari Zone",
        hub_id: "3",
        thumb_image: "papi_hills_thumb.jpg",
        path: "",
        latitude: "17.1167",
        longitude: "81.6667",
        map_icon: "aUmbrellaBeach",
        slug: "papi-hills",
        approx_time_to_visit: "3 hours",
        map_image_path: "https://example.com/images/papi_hills.jpg",
        city: "Rajahmundry",
      },
      {
        id: "303",
        destination_name: "Dowleswaram Barrage",
        destination_category_id: "4",
        city_id: "303",
        name: "Landmark",
        hub_name: "East Godavari Zone",
        hub_id: "3",
        thumb_image: "dowleswaram_barrage_thumb.jpg",
        path: "",
        latitude: "16.9833",
        longitude: "81.7667",
        map_icon: "landmark.png",
        slug: "dowleswaram-barrage",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/dowleswaram_barrage.jpg",
        city: "Rajahmundry",
      },
      {
        id: "304",
        destination_name: "Annavaram Temple",
        destination_category_id: "2",
        city_id: "304",
        name: "Religious",
        hub_name: "East Godavari Zone",
        hub_id: "3",
        thumb_image: "annavaram_temple_thumb.jpg",
        path: "",
        latitude: "17.2833",
        longitude: "82.4000",
        map_icon: "FaRegFlag",
        slug: "annavaram-temple",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/annavaram_temple.jpg",
        city: "Annavaram",
      },
      {
        id: "305",
        destination_name: "Coringa Wildlife Sanctuary",
        destination_category_id: "5",
        city_id: "305",
        name: "Wildlife",
        hub_name: "East Godavari Zone",
        hub_id: "3",
        thumb_image: "coringa_sanctuary_thumb.jpg",
        path: "",
        latitude: "16.8333",
        longitude: "82.2333",
        map_icon: "wildlife.png",
        slug: "coringa-wildlife-sanctuary",
        approx_time_to_visit: "3 hours",
        map_image_path: "https://example.com/images/coringa_sanctuary.jpg",
        city: "Kakinada",
      },
    ],
  },
  {
    id: "4",
    district: "Guntur",
    places: [
      {
        id: "401",
        destination_name: "Amaravati Stupa",
        destination_category_id: "1",
        city_id: "401",
        name: "Heritage",
        hub_name: "Guntur Zone",
        hub_id: "4",
        thumb_image: "amaravati_stupa_thumb.jpg",
        path: "",
        latitude: "16.5667",
        longitude: "80.3500",
        map_icon: "FaLandmark",
        slug: "amaravati-stupa",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/amaravati_stupa.jpg",
        city: "Amaravati",
      },
      {
        id: "402",
        destination_name: "Undavalli Caves",
        destination_category_id: "1",
        city_id: "402",
        name: "Heritage",
        hub_name: "Guntur Zone",
        hub_id: "4",
        thumb_image: "undavalli_caves_thumb.jpg",
        path: "",
        latitude: "16.4957",
        longitude: "80.5797",
        map_icon: "FaLandmark",
        slug: "undavalli-caves",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/undavalli_caves.jpg",
        city: "Guntur",
      },
      {
        id: "403",
        destination_name: "Kondaveedu Fort",
        destination_category_id: "1",
        city_id: "403",
        name: "Heritage",
        hub_name: "Guntur Zone",
        hub_id: "4",
        thumb_image: "kondaveedu_fort_thumb.jpg",
        path: "",
        latitude: "16.2500",
        longitude: "80.2500",
        map_icon: "FaLandmark",
        slug: "kondaveedu-fort",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/kondaveedu_fort.jpg",
        city: "Guntur",
      },
      {
        id: "404",
        destination_name: "Mangalagiri Temple",
        destination_category_id: "2",
        city_id: "404",
        name: "Religious",
        hub_name: "Guntur Zone",
        hub_id: "4",
        thumb_image: "mangalagiri_temple_thumb.jpg",
        path: "",
        latitude: "16.4333",
        longitude: "80.5667",
        map_icon: "FaRegFlag",
        slug: "mangalagiri-temple",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/mangalagiri_temple.jpg",
        city: "Mangalagiri",
      },
      {
        id: "405",
        destination_name: "Uppalapadu Bird Sanctuary",
        destination_category_id: "5",
        city_id: "405",
        name: "Wildlife",
        hub_name: "Guntur Zone",
        hub_id: "4",
        thumb_image: "uppalaradu_sanctuary_thumb.jpg",
        path: "",
        latitude: "16.3000",
        longitude: "80.4667",
        map_icon: "wildlife.png",
        slug: "uppalaradu-bird-sanctuary",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/uppalaradu_sanctuary.jpg",
        city: "Guntur",
      },
    ],
  },
  {
    id: "5",
    district: "Kadapa",
    places: [
      {
        id: "501",
        destination_name: "Gandikota",
        destination_category_id: "1",
        city_id: "501",
        name: "Heritage",
        hub_name: "Kadapa Zone",
        hub_id: "5",
        thumb_image: "gandikota_thumb.jpg",
        path: "",
        latitude: "14.8151",
        longitude: "78.2813",
        map_icon: "FaLandmark",
        slug: "gandikota",
        approx_time_to_visit: "3 hours",
        map_image_path:
          "https://tse1.mm.bing.net/th?id=OIP._EsJTZtjFEZLu9aA7zEKFgHaFj&pid=Api",
        city: "Kadapa",
      },
      {
        id: "502",
        destination_name: "Belum Caves",
        destination_category_id: "3",
        city_id: "502",
        name: "Nature",
        hub_name: "Kadapa Zone",
        hub_id: "5",
        thumb_image: "belum_caves_thumb.jpg",
        path: "",
        latitude: "15.1000",
        longitude: "78.1167",
        map_icon: "aUmbrellaBeach",
        slug: "belum-caves",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/belum_caves.jpg",
        city: "Kadapa",
      },
      {
        id: "503",
        destination_name: "Pushpagiri Temple",
        destination_category_id: "2",
        city_id: "503",
        name: "Religious",
        hub_name: "Kadapa Zone",
        hub_id: "5",
        thumb_image: "pushpagiri_temple_thumb.jpg",
        path: "",
        latitude: "14.6000",
        longitude: "78.7667",
        map_icon: "FaRegFlag",
        slug: "pushpagiri-temple",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/pushpagiri_temple.jpg",
        city: "Kadapa",
      },
      {
        id: "504",
        destination_name: "Ameen Peer Dargah",
        destination_category_id: "2",
        city_id: "504",
        name: "Religious",
        hub_name: "Kadapa Zone",
        hub_id: "5",
        thumb_image: "ameen_peer_dargah_thumb.jpg",
        path: "",
        latitude: "14.4673",
        longitude: "78.8291",
        map_icon: "FaRegFlag",
        slug: "ameen-peer-dargah",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/ameen_peer_dargah.jpg",
        city: "Kadapa",
      },
      {
        id: "505",
        destination_name: "Sidhout Fort",
        destination_category_id: "1",
        city_id: "505",
        name: "Heritage",
        hub_name: "Kadapa Zone",
        hub_id: "5",
        thumb_image: "sidhout_fort_thumb.jpg",
        path: "",
        latitude: "14.4667",
        longitude: "78.9667",
        map_icon: "FaLandmark",
        slug: "sidhout-fort",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/sidhout_fort.jpg",
        city: "Kadapa",
      },
    ],
  },
  {
    id: "6",
    district: "Krishna",
    places: [
      {
        id: "601",
        destination_name: "Kanaka Durga Temple",
        destination_category_id: "2",
        city_id: "601",
        name: "Religious",
        hub_name: "Krishna Zone",
        hub_id: "6",
        thumb_image: "kanaka_durga_thumb.jpg",
        path: "",
        latitude: "16.5170",
        longitude: "80.6305",
        map_icon: "FaRegFlag",
        slug: "kanaka-durga-temple",
        approx_time_to_visit: "2 hours",
        map_image_path:
          "https://tse1.mm.bing.net/th?id=OIP.XsBaLWrFi6D5HVK_JnMfuAHaEK&pid=Api",
        city: "Vijayawada",
      },
      {
        id: "602",
        destination_name: "Prakasam Barrage",
        destination_category_id: "4",
        city_id: "602",
        name: "Landmark",
        hub_name: "Krishna Zone",
        hub_id: "6",
        thumb_image: "prakasam_barrage_thumb.jpg",
        path: "",
        latitude: "16.5058",
        longitude: "80.6052",
        map_icon: "landmark.png",
        slug: "prakasam-barrage",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/prakasam_barrage.jpg",
        city: "Vijayawada",
      },
      {
        id: "603",
        destination_name: "Undavalli Caves",
        destination_category_id: "1",
        city_id: "603",
        name: "Heritage",
        hub_name: "Krishna Zone",
        hub_id: "6",
        thumb_image: "undavalli_caves_thumb.jpg",
        path: "",
        latitude: "16.4957",
        longitude: "80.5797",
        map_icon: "FaLandmark",
        slug: "undavalli-caves",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/undavalli_caves.jpg",
        city: "Vijayawada",
      },
      {
        id: "604",
        destination_name: "Bhavani Island",
        destination_category_id: "3",
        city_id: "604",
        name: "Nature",
        hub_name: "Krishna Zone",
        hub_id: "6",
        thumb_image: "bhavani_island_thumb.jpg",
        path: "",
        latitude: "16.5167",
        longitude: "80.5833",
        map_icon: "aUmbrellaBeach",
        slug: "bhavani-island",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/bhavani_island.jpg",
        city: "Vijayawada",
      },
      {
        id: "605",
        destination_name: "Hamsaladeevi Beach",
        destination_category_id: "6",
        city_id: "605",
        name: "Beach",
        hub_name: "Krishna Zone",
        hub_id: "6",
        thumb_image: "hamsaladeevi_beach_thumb.jpg",
        path: "",
        latitude: "15.9833",
        longitude: "81.1000",
        map_icon: "beach.png",
        slug: "hamsaladeevi-beach",
        approx_time_to_visit: "3 hours",
        map_image_path: "https://example.com/images/hamsaladeevi_beach.jpg",
        city: "Hamsaladeevi",
      },
    ],
  },
  {
    id: "7",
    district: "Kurnool",
    places: [
      {
        id: "701",
        destination_name: "Kurnool Fort",
        destination_category_id: "1",
        city_id: "701",
        name: "Heritage",
        hub_name: "Kurnool Zone",
        hub_id: "7",
        thumb_image: "kurnool_fort_thumb.jpg",
        path: "",
        latitude: "15.8333",
        longitude: "78.0333",
        map_icon: "FaLandmark",
        slug: "kurnool-fort",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/kurnool_fort.jpg",
        city: "Kurnool",
      },
      {
        id: "702",
        destination_name: "Oravakallu Rock Garden",
        destination_category_id: "3",
        city_id: "702",
        name: "Nature",
        hub_name: "Kurnool Zone",
        hub_id: "7",
        thumb_image: "oravakallu_thumb.jpg",
        path: "",
        latitude: "15.6833",
        longitude: "78.0167",
        map_icon: "aUmbrellaBeach",
        slug: "oravakallu-rock-garden",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/oravakallu.jpg",
        city: "Kurnool",
      },
      {
        id: "703",
        destination_name: "Belum Caves",
        destination_category_id: "3",
        city_id: "703",
        name: "Nature",
        hub_name: "Kurnool Zone",
        hub_id: "7",
        thumb_image: "belum_caves_thumb.jpg",
        path: "",
        latitude: "15.1000",
        longitude: "78.1167",
        map_icon: "aUmbrellaBeach",
        slug: "belum-caves",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/belum_caves.jpg",
        city: "Kurnool",
      },
      {
        id: "704",
        destination_name: "Ahobilam Temple",
        destination_category_id: "2",
        city_id: "704",
        name: "Religious",
        hub_name: "Kurnool Zone",
        hub_id: "7",
        thumb_image: "ahobilam_temple_thumb.jpg",
        path: "",
        latitude: "15.1333",
        longitude: "78.7167",
        map_icon: "FaRegFlag",
        slug: "ahobilam-temple",
        approx_time_to_visit: "3 hours",
        map_image_path: "https://example.com/images/ahobilam_temple.jpg",
        city: "Ahobilam",
      },
      {
        id: "705",
        destination_name: "Rollapadu Wildlife Sanctuary",
        destination_category_id: "5",
        city_id: "705",
        name: "Wildlife",
        hub_name: "Kurnool Zone",
        hub_id: "7",
        thumb_image: "rollapadu_sanctuary_thumb.jpg",
        path: "",
        latitude: "15.7167",
        longitude: "78.3167",
        map_icon: "wildlife.png",
        slug: "rollapadu-wildlife-sanctuary",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/rollapadu_sanctuary.jpg",
        city: "Kurnool",
      },
    ],
  },
  {
    id: "8",
    district: "Nellore",
    places: [
      {
        id: "801",
        destination_name: "Nellapattu Bird Sanctuary",
        destination_category_id: "5",
        city_id: "801",
        name: "Wildlife",
        hub_name: "Nellore Zone",
        hub_id: "8",
        thumb_image: "nellapattu_sanctuary_thumb.jpg",
        path: "",
        latitude: "14.4167",
        longitude: "80.0167",
        map_icon: "wildlife.png",
        slug: "nellapattu-bird-sanctuary",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/nellapattu_sanctuary.jpg",
        city: "Nellore",
      },
      {
        id: "802",
        destination_name: "Sri Ranganathaswamy Temple",
        destination_category_id: "2",
        city_id: "802",
        name: "Religious",
        hub_name: "Nellore Zone",
        hub_id: "8",
        thumb_image: "ranganathaswamy_temple_thumb.jpg",
        path: "",
        latitude: "14.4500",
        longitude: "79.9833",
        map_icon: "FaRegFlag",
        slug: "sri-ranganathaswamy-temple",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/ranganathaswamy_temple.jpg",
        city: "Nellore",
      },
      {
        id: "803",
        destination_name: "Pulicat Lake",
        destination_category_id: "3",
        city_id: "803",
        name: "Nature",
        hub_name: "Nellore Zone",
        hub_id: "8",
        thumb_image: "pulicat_lake_thumb.jpg",
        path: "",
        latitude: "13.6667",
        longitude: "80.3167",
        map_icon: "aUmbrellaBeach",
        slug: "pulicat-lake",
        approx_time_to_visit: "3 hours",
        map_image_path: "https://example.com/images/pulicat_lake.jpg",
        city: "Nellore",
      },
      {
        id: "804",
        destination_name: "Mypadu Beach",
        destination_category_id: "6",
        city_id: "804",
        name: "Beach",
        hub_name: "Nellore Zone",
        hub_id: "8",
        thumb_image: "mypadu_beach_thumb.jpg",
        path: "",
        latitude: "14.5000",
        longitude: "80.1667",
        map_icon: "beach.png",
        slug: "mypadu-beach",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/mypadu_beach.jpg",
        city: "Nellore",
      },
      {
        id: "805",
        destination_name: "Udayagiri Fort",
        destination_category_id: "1",
        city_id: "805",
        name: "Heritage",
        hub_name: "Nellore Zone",
        hub_id: "8",
        thumb_image: "udayagiri_fort_thumb.jpg",
        path: "",
        latitude: "14.8667",
        longitude: "79.3167",
        map_icon: "FaLandmark",
        slug: "udayagiri-fort",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/udayagiri_fort.jpg",
        city: "Udayagiri",
      },
    ],
  },
  {
    id: "9",
    district: "Prakasam",
    places: [
      {
        id: "901",
        destination_name: "Chandavaram Buddhist Site",
        destination_category_id: "1",
        city_id: "901",
        name: "Heritage",
        hub_name: "Prakasam Zone",
        hub_id: "9",
        thumb_image: "chandavaram_site_thumb.jpg",
        path: "",
        latitude: "15.5833",
        longitude: "79.9167",
        map_icon: "FaLandmark",
        slug: "chandavaram-buddhist-site",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/chandavaram_site.jpg",
        city: "Chandavaram",
      },
      {
        id: "902",
        destination_name: "Kothapatnam Beach",
        destination_category_id: "6",
        city_id: "902",
        name: "Beach",
        hub_name: "Prakasam Zone",
        hub_id: "9",
        thumb_image: "kothapatnam_beach_thumb.jpg",
        path: "",
        latitude: "15.4667",
        longitude: "80.1333",
        map_icon: "beach.png",
        slug: "kothapatnam-beach",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/kothapatnam_beach.jpg",
        city: "Kothapatnam",
      },
      {
        id: "903",
        destination_name: "Markapur Chennakesava Temple",
        destination_category_id: "2",
        city_id: "903",
        name: "Religious",
        hub_name: "Prakasam Zone",
        hub_id: "9",
        thumb_image: "markapur_temple_thumb.jpg",
        path: "",
        latitude: "15.7333",
        longitude: "79.2667",
        map_icon: "FaRegFlag",
        slug: "markapur-chennakesava-temple",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/markapur_temple.jpg",
        city: "Markapur",
      },
      {
        id: "904",
        destination_name: "Tripurantakam Temple",
        destination_category_id: "2",
        city_id: "904",
        name: "Religious",
        hub_name: "Prakasam Zone",
        hub_id: "9",
        thumb_image: "tripurantakam_temple_thumb.jpg",
        path: "",
        latitude: "16.0000",
        longitude: "79.6667",
        map_icon: "FaRegFlag",
        slug: "tripurantakam-temple",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/tripurantakam_temple.jpg",
        city: "Tripurantakam",
      },
      {
        id: "905",
        destination_name: "Bhairavakona Caves",
        destination_category_id: "3",
        city_id: "905",
        name: "Nature",
        hub_name: "Prakasam Zone",
        hub_id: "9",
        thumb_image: "bhairavakona_caves_thumb.jpg",
        path: "",
        latitude: "15.3833",
        longitude: "79.8333",
        map_icon: "aUmbrellaBeach",
        slug: "bhairavakona-caves",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/bhairavakona_caves.jpg",
        city: "Prakasam",
      },
    ],
  },
  {
    id: "10",
    district: "Srikakulam",
    places: [
      {
        id: "1001",
        destination_name: "Srikurmam Temple",
        destination_category_id: "2",
        city_id: "1001",
        name: "Religious",
        hub_name: "Srikakulam Zone",
        hub_id: "10",
        thumb_image: "srikurmam_temple_thumb.jpg",
        path: "",
        latitude: "18.2667",
        longitude: "84.0167",
        map_icon: "FaRegFlag",
        slug: "srikurmam-temple",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/srikurmam_temple.jpg",
        city: "Srikakulam",
      },
      {
        id: "1002",
        destination_name: "Arasavalli Sun Temple",
        destination_category_id: "2",
        city_id: "1002",
        name: "Religious",
        hub_name: "Srikakulam Zone",
        hub_id: "10",
        thumb_image: "arasavalli_temple_thumb.jpg",
        path: "",
        latitude: "18.2833",
        longitude: "83.9000",
        map_icon: "FaRegFlag",
        slug: "arasavalli-sun-temple",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/arasavalli_temple.jpg",
        city: "Srikakulam",
      },
      {
        id: "1003",
        destination_name: "Baruva Beach",
        destination_category_id: "6",
        city_id: "1003",
        name: "Beach",
        hub_name: "Srikakulam Zone",
        hub_id: "10",
        thumb_image: "baruva_beach_thumb.jpg",
        path: "",
        latitude: "18.8667",
        longitude: "84.5833",
        map_icon: "beach.png",
        slug: "baruva-beach",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/baruva_beach.jpg",
        city: "Baruva",
      },
      {
        id: "1004",
        destination_name: "Sangameswara Temple",
        destination_category_id: "2",
        city_id: "1004",
        name: "Religious",
        hub_name: "Srikakulam Zone",
        hub_id: "10",
        thumb_image: "sangameswara_temple_thumb.jpg",
        path: "",
        latitude: "18.6667",
        longitude: "84.3167",
        map_icon: "FaRegFlag",
        slug: "sangameswara-temple",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/sangameswara_temple.jpg",
        city: "Sangam",
      },
      {
        id: "1005",
        destination_name: "Kalingapatnam Beach",
        destination_category_id: "6",
        city_id: "1005",
        name: "Beach",
        hub_name: "Srikakulam Zone",
        hub_id: "10",
        thumb_image: "kalingapatnam_beach_thumb.jpg",
        path: "",
        latitude: "18.3333",
        longitude: "84.1333",
        map_icon: "beach.png",
        slug: "kalingapatnam-beach",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/kalingapatnam_beach.jpg",
        city: "Kalingapatnam",
      },
    ],
  },
  {
    id: "11",
    district: "Visakhapatnam",
    places: [
      {
        id: "1101",
        destination_name: "Araku Valley",
        destination_category_id: "3",
        city_id: "1101",
        name: "Nature",
        hub_name: "Visakhapatnam Zone",
        hub_id: "11",
        thumb_image: "araku_valley_thumb.jpg",
        path: "",
        latitude: "18.3333",
        longitude: "82.8667",
        map_icon: "aUmbrellaBeach",
        slug: "araku-valley",
        approx_time_to_visit: "4 hours",
        map_image_path:
          "https://tse2.mm.bing.net/th?id=OIP.QdrtRqwTrAWSXRtAabEkEQHaE1&pid=Api",
        city: "Visakhapatnam",
      },
      {
        id: "1102",
        destination_name: "Borra Caves",
        destination_category_id: "3",
        city_id: "1102",
        name: "Nature",
        hub_name: "Visakhapatnam Zone",
        hub_id: "11",
        thumb_image: "borra_caves_thumb.jpg",
        path: "",
        latitude: "18.2833",
        longitude: "83.0333",
        map_icon: "aUmbrellaBeach",
        slug: "borra-caves",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/borra_caves.jpg",
        city: "Visakhapatnam",
      },
      {
        id: "1103",
        destination_name: "RK Beach",
        destination_category_id: "6",
        city_id: "1103",
        name: "Beach",
        hub_name: "Visakhapatnam Zone",
        hub_id: "11",
        thumb_image: "rk_beach_thumb.jpg",
        path: "",
        latitude: "17.7145",
        longitude: "83.3200",
        map_icon: "beach.png",
        slug: "rk-beach",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/rk_beach.jpg",
        city: "Visakhapatnam",
      },
      {
        id: "1104",
        destination_name: "Kailasagiri Hill Park",
        destination_category_id: "3",
        city_id: "1104",
        name: "Nature",
        hub_name: "Visakhapatnam Zone",
        hub_id: "11",
        thumb_image: "kailasagiri_hill_thumb.jpg",
        path: "",
        latitude: "17.7490",
        longitude: "83.3410",
        map_icon: "aUmbrellaBeach",
        slug: "kailasagiri-hill-park",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/kailasagiri_hill.jpg",
        city: "Visakhapatnam",
      },
      {
        id: "1105",
        destination_name: "Simhachalam Temple",
        destination_category_id: "2",
        city_id: "1105",
        name: "Religious",
        hub_name: "Visakhapatnam Zone",
        hub_id: "11",
        thumb_image: "simhachalam_temple_thumb.jpg",
        path: "",
        latitude: "17.7667",
        longitude: "83.2500",
        map_icon: "FaRegFlag",
        slug: "simhachalam-temple",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/simhachalam_temple.jpg",
        city: "Visakhapatnam",
      },
    ],
  },
  {
    id: "12",
    district: "Vizianagaram",
    places: [
      {
        id: "1201",
        destination_name: "Vizianagaram Fort",
        destination_category_id: "1",
        city_id: "1201",
        name: "Heritage",
        hub_name: "Vizianagaram Zone",
        hub_id: "12",
        thumb_image: "vizianagaram_fort_thumb.jpg",
        path: "",
        latitude: "18.1167",
        longitude: "83.4000",
        map_icon: "FaLandmark",
        slug: "vizianagaram-fort",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/vizianagaram_fort.jpg",
        city: "Vizianagaram",
      },
      {
        id: "1202",
        destination_name: "Ramanarayanam Temple",
        destination_category_id: "2",
        city_id: "1202",
        name: "Religious",
        hub_name: "Vizianagaram Zone",
        hub_id: "12",
        thumb_image: "ramanarayanam_temple_thumb.jpg",
        path: "",
        latitude: "18.1333",
        longitude: "83.3833",
        map_icon: "FaRegFlag",
        slug: "ramanarayanam-temple",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/ramanarayanam_temple.jpg",
        city: "Vizianagaram",
      },
      {
        id: "1203",
        destination_name: "Gosthani River",
        destination_category_id: "3",
        city_id: "1203",
        name: "Nature",
        hub_name: "Vizianagaram Zone",
        hub_id: "12",
        thumb_image: "gosthani_river_thumb.jpg",
        path: "",
        latitude: "18.1000",
        longitude: "83.4167",
        map_icon: "aUmbrellaBeach",
        slug: "gosthani-river",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/gosthani_river.jpg",
        city: "Vizianagaram",
      },
      {
        id: "1204",
        destination_name: "Punpun Hill",
        destination_category_id: "3",
        city_id: "1204",
        name: "Nature",
        hub_name: "Vizianagaram Zone",
        hub_id: "12",
        thumb_image: "punpun_hill_thumb.jpg",
        path: "",
        latitude: "18.2000",
        longitude: "83.3667",
        map_icon: "aUmbrellaBeach",
        slug: "punpun-hill",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/punpun_hill.jpg",
        city: "Vizianagaram",
      },
      {
        id: "1205",
        destination_name: "Bobbili Fort",
        destination_category_id: "1",
        city_id: "1205",
        name: "Heritage",
        hub_name: "Vizianagaram Zone",
        hub_id: "12",
        thumb_image: "bobbili_fort_thumb.jpg",
        path: "",
        latitude: "18.5667",
        longitude: "83.3667",
        map_icon: "FaLandmark",
        slug: "bobbili-fort",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/bobbili_fort.jpg",
        city: "Bobbili",
      },
    ],
  },
  {
    id: "13",
    district: "West Godavari",
    places: [
      {
        id: "1301",
        destination_name: "Kolleru Lake",
        destination_category_id: "3",
        city_id: "1301",
        name: "Nature",
        hub_name: "West Godavari Zone",
        hub_id: "13",
        thumb_image: "kolleru_lake_thumb.jpg",
        path: "",
        latitude: "16.6167",
        longitude: "81.2000",
        map_icon: "aUmbrellaBeach",
        slug: "kolleru-lake",
        approx_time_to_visit: "3 hours",
        map_image_path: "https://example.com/images/kolleru_lake.jpg",
        city: "Eluru",
      },
      {
        id: "1302",
        destination_name: "Dwaraka Tirumala Temple",
        destination_category_id: "2",
        city_id: "1302",
        name: "Religious",
        hub_name: "West Godavari Zone",
        hub_id: "13",
        thumb_image: "dwaraka_tirumala_thumb.jpg",
        path: "",
        latitude: "16.9500",
        longitude: "81.2667",
        map_icon: "FaRegFlag",
        slug: "dwaraka-tirumala-temple",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/dwaraka_tirumala.jpg",
        city: "Dwaraka Tirumala",
      },
      {
        id: "1303",
        destination_name: "Pattiseema",
        destination_category_id: "3",
        city_id: "1303",
        name: "Nature",
        hub_name: "West Godavari Zone",
        hub_id: "13",
        thumb_image: "pattiseema_thumb.jpg",
        path: "",
        latitude: "16.8167",
        longitude: "81.5833",
        map_icon: "aUmbrellaBeach",
        slug: "pattiseema",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/pattiseema.jpg",
        city: "Pattiseema",
      },
      {
        id: "1304",
        destination_name: "Somaramam Temple",
        destination_category_id: "2",
        city_id: "1304",
        name: "Religious",
        hub_name: "West Godavari Zone",
        hub_id: "13",
        thumb_image: "somaramam_temple_thumb.jpg",
        path: "",
        latitude: "16.5500",
        longitude: "81.5167",
        map_icon: "FaRegFlag",
        slug: "somaramam-temple",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/somaramam_temple.jpg",
        city: "Bhimavaram",
      },
      {
        id: "1305",
        destination_name: "Eluru Ashram",
        destination_category_id: "2",
        city_id: "1305",
        name: "Religious",
        hub_name: "West Godavari Zone",
        hub_id: "13",
        thumb_image: "eluru_ashram_thumb.jpg",
        path: "",
        latitude: "16.7167",
        longitude: "81.1000",
        map_icon: "FaRegFlag",
        slug: "eluru-ashram",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/eluru_ashram.jpg",
        city: "Eluru",
      },
    ],
  },
  {
    id: "14",
    district: "Alluri Sitharama Raju",
    places: [
      {
        id: "1401",
        destination_name: "Lambasingi",
        destination_category_id: "3",
        city_id: "1401",
        name: "Nature",
        hub_name: "Alluri Zone",
        hub_id: "14",
        thumb_image: "lambasingi_thumb.jpg",
        path: "",
        latitude: "18.2667",
        longitude: "82.4667",
        map_icon: "aUmbrellaBeach",
        slug: "lambasingi",
        approx_time_to_visit: "3 hours",
        map_image_path: "https://example.com/images/lambasingi.jpg",
        city: "Lambasingi",
      },
      {
        id: "1402",
        destination_name: "Vanajangi Hills",
        destination_category_id: "3",
        city_id: "1402",
        name: "Nature",
        hub_name: "Alluri Zone",
        hub_id: "14",
        thumb_image: "vanajangi_hills_thumb.jpg",
        path: "",
        latitude: "18.0833",
        longitude: "82.6667",
        map_icon: "aUmbrellaBeach",
        slug: "vanajangi-hills",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/vanajangi_hills.jpg",
        city: "Paderu",
      },
      {
        id: "1403",
        destination_name: "Katiki Waterfalls",
        destination_category_id: "3",
        city_id: "1403",
        name: "Nature",
        hub_name: "Alluri Zone",
        hub_id: "14",
        thumb_image: "katiki_waterfalls_thumb.jpg",
        path: "",
        latitude: "18.3167",
        longitude: "82.8667",
        map_icon: "aUmbrellaBeach",
        slug: "katiki-waterfalls",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/katiki_waterfalls.jpg",
        city: "Araku",
      },
      {
        id: "1404",
        destination_name: "Padmapuram Gardens",
        destination_category_id: "3",
        city_id: "1404",
        name: "Nature",
        hub_name: "Alluri Zone",
        hub_id: "14",
        thumb_image: "padmapuram_gardens_thumb.jpg",
        path: "",
        latitude: "18.3333",
        longitude: "82.8667",
        map_icon: "aUmbrellaBeach",
        slug: "padmapuram-gardens",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/padmapuram_gardens.jpg",
        city: "Araku",
      },
      {
        id: "1405",
        destination_name: "Tribal Museum Araku",
        destination_category_id: "7",
        city_id: "1405",
        name: "Cultural",
        hub_name: "Alluri Zone",
        hub_id: "14",
        thumb_image: "tribal_museum_araku_thumb.jpg",
        path: "",
        latitude: "18.3333",
        longitude: "82.8667",
        map_icon: "cultural.png",
        slug: "tribal-museum-araku",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/tribal_museum_araku.jpg",
        city: "Araku",
      },
    ],
  },
  {
    id: "15",
    district: "Anakapalli",
    places: [
      {
        id: "1501",
        destination_name: "Bojjannakonda",
        destination_category_id: "1",
        city_id: "1501",
        name: "Heritage",
        hub_name: "Anakapalli Zone",
        hub_id: "15",
        thumb_image: "bojjannakonda_thumb.jpg",
        path: "",
        latitude: "17.7167",
        longitude: "83.0333",
        map_icon: "FaLandmark",
        slug: "bojjannakonda",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/bojjannakonda.jpg",
        city: "Anakapalli",
      },
      {
        id: "1502",
        destination_name: "Kondakarla Ava",
        destination_category_id: "3",
        city_id: "1502",
        name: "Nature",
        hub_name: "Anakapalli Zone",
        hub_id: "15",
        thumb_image: "kondakarla_ava_thumb.jpg",
        path: "",
        latitude: "17.6167",
        longitude: "82.9667",
        map_icon: "aUmbrellaBeach",
        slug: "kondakarla-ava",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/kondakarla_ava.jpg",
        city: "Anakapalli",
      },
      {
        id: "1503",
        destination_name: "Devipuram Temple",
        destination_category_id: "2",
        city_id: "1503",
        name: "Religious",
        hub_name: "Anakapalli Zone",
        hub_id: "15",
        thumb_image: "devipuram_temple_thumb.jpg",
        path: "",
        latitude: "17.6667",
        longitude: "83.0833",
        map_icon: "FaRegFlag",
        slug: "devipuram-temple",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/devipuram_temple.jpg",
        city: "Anakapalli",
      },
      {
        id: "1504",
        destination_name: "Anakapalli Ghosha Caves",
        destination_category_id: "1",
        city_id: "1504",
        name: "Heritage",
        hub_name: "Anakapalli Zone",
        hub_id: "15",
        thumb_image: "ghosha_caves_thumb.jpg",
        path: "",
        latitude: "17.6833",
        longitude: "83.0167",
        map_icon: "FaLandmark",
        slug: "anakapalli-ghosha-caves",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/ghosha_caves.jpg",
        city: "Anakapalli",
      },
      {
        id: "1505",
        destination_name: "Pavuralakonda",
        destination_category_id: "1",
        city_id: "1505",
        name: "Heritage",
        hub_name: "Anakapalli Zone",
        hub_id: "15",
        thumb_image: "pavuralakonda_thumb.jpg",
        path: "",
        latitude: "17.7500",
        longitude: "83.0667",
        map_icon: "FaLandmark",
        slug: "pavuralakonda",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/pavuralakonda.jpg",
        city: "Anakapalli",
      },
    ],
  },
  {
    id: "16",
    district: "Bapatla",
    places: [
      {
        id: "1601",
        destination_name: "Bapatla Beach",
        destination_category_id: "6",
        city_id: "1601",
        name: "Beach",
        hub_name: "Bapatla Zone",
        hub_id: "16",
        thumb_image: "bapatla_beach_thumb.jpg",
        path: "",
        latitude: "15.9000",
        longitude: "80.4667",
        map_icon: "beach.png",
        slug: "bapatla-beach",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/bapatla_beach.jpg",
        city: "Bapatla",
      },
      {
        id: "1602",
        destination_name: "Suryalanka Beach",
        destination_category_id: "6",
        city_id: "1602",
        name: "Beach",
        hub_name: "Bapatla Zone",
        hub_id: "16",
        thumb_image: "suryalanka_beach_thumb.jpg",
        path: "",
        latitude: "15.8333",
        longitude: "80.5000",
        map_icon: "beach.png",
        slug: "suryalanka-beach",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/suryalanka_beach.jpg",
        city: "Suryalanka",
      },
      {
        id: "1603",
        destination_name: "Bhavanarayana Swamy Temple",
        destination_category_id: "2",
        city_id: "1603",
        name: "Religious",
        hub_name: "Bapatla Zone",
        hub_id: "16",
        thumb_image: "bhavanarayana_temple_thumb.jpg",
        path: "",
        latitude: "15.9167",
        longitude: "80.4667",
        map_icon: "FaRegFlag",
        slug: "bhavanarayana-swamy-temple",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/bhavanarayana_temple.jpg",
        city: "Bapatla",
      },
      {
        id: "1604",
        destination_name: "Vodarevu Beach",
        destination_category_id: "6",
        city_id: "1604",
        name: "Beach",
        hub_name: "Bapatla Zone",
        hub_id: "16",
        thumb_image: "vodarevu_beach_thumb.jpg",
        path: "",
        latitude: "15.8167",
        longitude: "80.6167",
        map_icon: "beach.png",
        slug: "vodarevu-beach",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/vodarevu_beach.jpg",
        city: "Vodarevu",
      },
      {
        id: "1605",
        destination_name: "Chirala Handlooms",
        destination_category_id: "7",
        city_id: "1605",
        name: "Cultural",
        hub_name: "Bapatla Zone",
        hub_id: "16",
        thumb_image: "chirala_handlooms_thumb.jpg",
        path: "",
        latitude: "15.8167",
        longitude: "80.3500",
        map_icon: "cultural.png",
        slug: "chirala-handlooms",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/chirala_handlooms.jpg",
        city: "Chirala",
      },
    ],
  },
  {
    id: "17",
    district: "Dr. B.R. Ambedkar Konaseema",
    places: [
      {
        id: "1701",
        destination_name: "Antarvedi Lakshmi Narasimha Temple",
        destination_category_id: "2",
        city_id: "1701",
        name: "Religious",
        hub_name: "Konaseema Zone",
        hub_id: "17",
        thumb_image: "antarvedi_temple_thumb.jpg",
        path: "",
        latitude: "16.3333",
        longitude: "81.7333",
        map_icon: "FaRegFlag",
        slug: "antarvedi-lakshmi-narasimha-temple",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/antarvedi_temple.jpg",
        city: "Antarvedi",
      },
      {
        id: "1702",
        destination_name: "Adurru Buddhist Site",
        destination_category_id: "1",
        city_id: "1702",
        name: "Heritage",
        hub_name: "Konaseema Zone",
        hub_id: "17",
        thumb_image: "adurru_site_thumb.jpg",
        path: "",
        latitude: "16.5833",
        longitude: "81.9167",
        map_icon: "FaLandmark",
        slug: "adurru-buddhist-site",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/adurru_site.jpg",
        city: "Adurru",
      },
      {
        id: "1703",
        destination_name: "Konaseema Backwaters",
        destination_category_id: "3",
        city_id: "1703",
        name: "Nature",
        hub_name: "Konaseema Zone",
        hub_id: "17",
        thumb_image: "konaseema_backwaters_thumb.jpg",
        path: "",
        latitude: "16.5833",
        longitude: "82.0167",
        map_icon: "aUmbrellaBeach",
        slug: "konaseema-backwaters",
        approx_time_to_visit: "3 hours",
        map_image_path: "https://example.com/images/konaseema_backwaters.jpg",
        city: "Amalapuram",
      },
      {
        id: "1704",
        destination_name: "Hope Island",
        destination_category_id: "3",
        city_id: "1704",
        name: "Nature",
        hub_name: "Konaseema Zone",
        hub_id: "17",
        thumb_image: "hope_island_thumb.jpg",
        path: "",
        latitude: "16.4667",
        longitude: "81.9167",
        map_icon: "aUmbrellaBeach",
        slug: "hope-island",
        approx_time_to_visit: "3 hours",
        map_image_path: "https://example.com/images/hope_island.jpg",
        city: "Konaseema",
      },
      {
        id: "1705",
        destination_name: "Maredumilli",
        destination_category_id: "3",
        city_id: "1705",
        name: "Nature",
        hub_name: "Konaseema Zone",
        hub_id: "17",
        thumb_image: "maredumilli_thumb.jpg",
        path: "",
        latitude: "17.6000",
        longitude: "82.3333",
        map_icon: "aUmbrellaBeach",
        slug: "maredumilli",
        approx_time_to_visit: "3 hours",
        map_image_path: "https://example.com/images/maredumilli.jpg",
        city: "Maredumilli",
      },
    ],
  },
  {
    id: "18",
    district: "Eluru",
    places: [
      {
        id: "1801",
        destination_name: "Kolleru Lake",
        destination_category_id: "3",
        city_id: "1801",
        name: "Nature",
        hub_name: "Eluru Zone",
        hub_id: "18",
        thumb_image: "kolleru_lake_thumb.jpg",
        path: "",
        latitude: "16.6167",
        longitude: "81.2000",
        map_icon: "aUmbrellaBeach",
        slug: "kolleru-lake",
        approx_time_to_visit: "3 hours",
        map_image_path: "https://example.com/images/kolleru_lake.jpg",
        city: "Eluru",
      },
      {
        id: "1802",
        destination_name: "Eluru Ashram",
        destination_category_id: "2",
        city_id: "1802",
        name: "Religious",
        hub_name: "Eluru Zone",
        hub_id: "18",
        thumb_image: "eluru_ashram_thumb.jpg",
        path: "",
        latitude: "16.7167",
        longitude: "81.1000",
        map_icon: "FaRegFlag",
        slug: "eluru-ashram",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/eluru_ashram.jpg",
        city: "Eluru",
      },
      {
        id: "1803",
        destination_name: "Papi Hills",
        destination_category_id: "3",
        city_id: "1803",
        name: "Nature",
        hub_name: "Eluru Zone",
        hub_id: "18",
        thumb_image: "papi_hills_thumb.jpg",
        path: "",
        latitude: "17.1167",
        longitude: "81.6667",
        map_icon: "aUmbrellaBeach",
        slug: "papi-hills",
        approx_time_to_visit: "3 hours",
        map_image_path: "https://example.com/images/papi_hills.jpg",
        city: "Eluru",
      },
      {
        id: "1804",
        destination_name: "Dwaraka Tirumala Temple",
        destination_category_id: "2",
        city_id: "1804",
        name: "Religious",
        hub_name: "Eluru Zone",
        hub_id: "18",
        thumb_image: "dwaraka_tirumala_thumb.jpg",
        path: "",
        latitude: "16.9500",
        longitude: "81.2667",
        map_icon: "FaRegFlag",
        slug: "dwaraka-tirumala-temple",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/dwaraka_tirumala.jpg",
        city: "Dwaraka Tirumala",
      },
      {
        id: "1805",
        destination_name: "Guntupalli Caves",
        destination_category_id: "1",
        city_id: "1805",
        name: "Heritage",
        hub_name: "Eluru Zone",
        hub_id: "18",
        thumb_image: "guntupalli_caves_thumb.jpg",
        path: "",
        latitude: "16.7833",
        longitude: "81.1167",
        map_icon: "FaLandmark",
        slug: "guntupalli-caves",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/guntupalli_caves.jpg",
        city: "Guntupalli",
      },
    ],
  },
  {
    id: "19",
    district: "Kakinada",
    places: [
      {
        id: "1901",
        destination_name: "Coringa Wildlife Sanctuary",
        destination_category_id: "5",
        city_id: "1901",
        name: "Wildlife",
        hub_name: "Kakinada Zone",
        hub_id: "19",
        thumb_image: "coringa_sanctuary_thumb.jpg",
        path: "",
        latitude: "16.8333",
        longitude: "82.2333",
        map_icon: "wildlife.png",
        slug: "coringa-wildlife-sanctuary",
        approx_time_to_visit: "3 hours",
        map_image_path: "https://example.com/images/coringa_sanctuary.jpg",
        city: "Kakinada",
      },
      {
        id: "1902",
        destination_name: "Kakinada Beach",
        destination_category_id: "6",
        city_id: "1902",
        name: "Beach",
        hub_name: "Kakinada Zone",
        hub_id: "19",
        thumb_image: "kakinada_beach_thumb.jpg",
        path: "",
        latitude: "16.9833",
        longitude: "82.2500",
        map_icon: "beach.png",
        slug: "kakinada-beach",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/kakinada_beach.jpg",
        city: "Kakinada",
      },
      {
        id: "1903",
        destination_name: "Uppada Beach",
        destination_category_id: "6",
        city_id: "1903",
        name: "Beach",
        hub_name: "Kakinada Zone",
        hub_id: "19",
        thumb_image: "uppada_beach_thumb.jpg",
        path: "",
        latitude: "17.0833",
        longitude: "82.3333",
        map_icon: "beach.png",
        slug: "uppada-beach",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/uppada_beach.jpg",
        city: "Uppada",
      },
      {
        id: "1904",
        destination_name: "Hope Island",
        destination_category_id: "3",
        city_id: "1904",
        name: "Nature",
        hub_name: "Kakinada Zone",
        hub_id: "19",
        thumb_image: "hope_island_thumb.jpg",
        path: "",
        latitude: "16.4667",
        longitude: "81.9167",
        map_icon: "aUmbrellaBeach",
        slug: "hope-island",
        approx_time_to_visit: "3 hours",
        map_image_path: "https://example.com/images/hope_island.jpg",
        city: "Kakinada",
      },
      {
        id: "1905",
        destination_name: "Pithapuram Temple",
        destination_category_id: "2",
        city_id: "1905",
        name: "Religious",
        hub_name: "Kakinada Zone",
        hub_id: "19",
        thumb_image: "pithapuram_temple_thumb.jpg",
        path: "",
        latitude: "17.1167",
        longitude: "82.2667",
        map_icon: "FaRegFlag",
        slug: "pithapuram-temple",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/pithapuram_temple.jpg",
        city: "Pithapuram",
      },
    ],
  },
  {
    id: "20",
    district: "Nandyal",
    places: [
      {
        id: "2001",
        destination_name: "Yaganti Temple",
        destination_category_id: "2",
        city_id: "2001",
        name: "Religious",
        hub_name: "Nandyal Zone",
        hub_id: "20",
        thumb_image: "yaganti_temple_thumb.jpg",
        path: "",
        latitude: "15.3500",
        longitude: "78.1333",
        map_icon: "FaRegFlag",
        slug: "yaganti-temple",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/yaganti_temple.jpg",
        city: "Yaganti",
      },
      {
        id: "2002",
        destination_name: "Mahanandi Temple",
        destination_category_id: "2",
        city_id: "2002",
        name: "Religious",
        hub_name: "Nandyal Zone",
        hub_id: "20",
        thumb_image: "mahanandi_temple_thumb.jpg",
        path: "",
        latitude: "15.4667",
        longitude: "78.6167",
        map_icon: "FaRegFlag",
        slug: "mahanandi-temple",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/mahanandi_temple.jpg",
        city: "Mahanandi",
      },
      {
        id: "2003",
        destination_name: "Nallamala Hills",
        destination_category_id: "3",
        city_id: "2003",
        name: "Nature",
        hub_name: "Nandyal Zone",
        hub_id: "20",
        thumb_image: "nallamala_hills_thumb.jpg",
        path: "",
        latitude: "15.6667",
        longitude: "78.6667",
        map_icon: "aUmbrellaBeach",
        slug: "nallamala-hills",
        approx_time_to_visit: "3 hours",
        map_image_path: "https://example.com/images/nallamala_hills.jpg",
        city: "Nandyal",
      },
      {
        id: "2004",
        destination_name: "Belum Caves",
        destination_category_id: "3",
        city_id: "2004",
        name: "Nature",
        hub_name: "Nandyal Zone",
        hub_id: "20",
        thumb_image: "belum_caves_thumb.jpg",
        path: "",
        latitude: "15.1000",
        longitude: "78.1167",
        map_icon: "aUmbrellaBeach",
        slug: "belum-caves",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/belum_caves.jpg",
        city: "Nandyal",
      },
      {
        id: "2005",
        destination_name: "Koilakuntla Fort",
        destination_category_id: "1",
        city_id: "2005",
        name: "Heritage",
        hub_name: "Nandyal Zone",
        hub_id: "20",
        thumb_image: "koilakuntla_fort_thumb.jpg",
        path: "",
        latitude: "15.2333",
        longitude: "78.3167",
        map_icon: "FaLandmark",
        slug: "koilakuntla-fort",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/koilakuntla_fort.jpg",
        city: "Koilakuntla",
      },
    ],
  },
  {
    id: "21",
    district: "NTR",
    places: [
      {
        id: "2101",
        destination_name: "Kanaka Durga Temple",
        destination_category_id: "2",
        city_id: "2101",
        name: "Religious",
        hub_name: "NTR Zone",
        hub_id: "21",
        thumb_image: "kanaka_durga_thumb.jpg",
        path: "",
        latitude: "16.5170",
        longitude: "80.6305",
        map_icon: "FaRegFlag",
        slug: "kanaka-durga-temple",
        approx_time_to_visit: "2 hours",
        map_image_path:
          "https://tse1.mm.bing.net/th?id=OIP.XsBaLWrFi6D5HVK_JnMfuAHaEK&pid=Api",
        city: "Vijayawada",
      },
      {
        id: "2102",
        destination_name: "Prakasam Barrage",
        destination_category_id: "4",
        city_id: "2102",
        name: "Landmark",
        hub_name: "NTR Zone",
        hub_id: "21",
        thumb_image: "prakasam_barrage_thumb.jpg",
        path: "",
        latitude: "16.5058",
        longitude: "80.6052",
        map_icon: "landmark.png",
        slug: "prakasam-barrage",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/prakasam_barrage.jpg",
        city: "Vijayawada",
      },
      {
        id: "2103",
        destination_name: "Undavalli Caves",
        destination_category_id: "1",
        city_id: "2103",
        name: "Heritage",
        hub_name: "NTR Zone",
        hub_id: "21",
        thumb_image: "undavalli_caves_thumb.jpg",
        path: "",
        latitude: "16.4957",
        longitude: "80.5797",
        map_icon: "FaLandmark",
        slug: "undavalli-caves",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/undavalli_caves.jpg",
        city: "Vijayawada",
      },
      {
        id: "2104",
        destination_name: "Bhavani Island",
        destination_category_id: "3",
        city_id: "2104",
        name: "Nature",
        hub_name: "NTR Zone",
        hub_id: "21",
        thumb_image: "bhavani_island_thumb.jpg",
        path: "",
        latitude: "16.5167",
        longitude: "80.5833",
        map_icon: "aUmbrellaBeach",
        slug: "bhavani-island",
        approx_time_to_visit: "2 hours",
        map_image_path: "https://example.com/images/bhavani_island.jpg",
        city: "Vijayawada",
      },
      {
        id: "2605",
        destination_name: "Vontimitta Kodandarama Temple",
        destination_category_id: "2",
        city_id: "2605",
        name: "Religious",
        hub_name: "YSR Zone",
        hub_id: "26",
        thumb_image: "vontimitta_temple_thumb.jpg",
        path: "",
        latitude: "14.3833",
        longitude: "78.9667",
        map_icon: "FaRegFlag",
        slug: "vontimitta-kodandarama-temple",
        approx_time_to_visit: "1 hour",
        map_image_path: "https://example.com/images/vontimitta_temple.jpg",
        city: "Vontimitta",
      },
    ],
  },
];
