export const fields = [
    { name: 'merchantId', label: 'Merchant ID', type: 'text' },
    { name: 'businessName', label: 'Business Name', type: 'text' },
    { name: 'registrationNumber', label: 'Registration Number', type: 'text' },
    { name: 'email', label: 'Email', type: 'email' },
    { name: 'contactPersonName', label: 'Contact Person Name', type: 'text' },
    { name: 'contactPhoneNumber', label: 'Contact Phone Number', type: 'text' },
    { name: 'businessAddress', label: 'Business Address', type: 'text' },
    { name: 'businessWebsite', label: 'Business Website', type: 'text' },
    { name: 'businessCategory', label: 'Business Category', type: 'text' },
    { name: 'incorporationDate', label: 'Incorporation Date', type: 'date' },
    { name: 'legalDocumentType', label: 'Legal Document Type', type: 'text' },
    { name: 'legalDocumentNumber', label: 'Legal Document Number', type: 'text' },
    { name: 'legalDocumentImageUrl', label: 'Legal Document URL', type: 'text' },
    { name: 'proofOfAddressDocumentType', label: 'Proof of Address Type', type: 'text' },
    { name: 'proofOfAddressDocumentNumber', label: 'Proof of Address Number', type: 'text' },
    { name: 'proofOfAddressDocumentImageUrl', label: 'Proof of Address URL', type: 'text' },
    { name: 'bankAccountNumber', label: 'Bank Account Number', type: 'text' },
    { name: 'bankIfscCode', label: 'Bank IFSC Code', type: 'text' },
    { name: 'bankAccountHolderName', label: 'Bank Account Holder Name', type: 'text' },
    { name: 'kycVerified', label: 'KYC Verified', type: 'checkbox' },
    { name: 'kycVerificationStatus', label: 'KYC Verification Status', type: 'text' },
    { name: 'enabled', label: 'Enabled', type: 'checkbox' },
  ];